# Generated by Django 4.0.2 on 2022-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song_data',
            name='data',
        ),
        migrations.AddField(
            model_name='song_data',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
