# Generated by Django 4.0.2 on 2022-02-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_song_data_data_song_data_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_data',
            name='record',
            field=models.BinaryField(),
        ),
    ]
