# Generated by Django 4.0.2 on 2022-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_song_data_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_data',
            name='record',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
